Fix unexpected end of input error
## Root cause : 
Hexo can not parse index.js because missing a new line in the end of index.js
## Error detail : 
ERROR Plugin load failed: hexo-all-minifier
E:\Coding\00.Project\asing1001.github.io\node_modules\hexo-all-minifier\index.js:54
}
^
SyntaxError: Unexpected end of input
    at Object.exports.runInThisContext (vm.js:53:16)
    at E:\Coding\00.Project\asing1001.github.io\node_modules\hexo\lib\hexo\index.js:227:17
    at tryCatcher (E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\promise.js:638:18)
    at E:\Coding\00.Project\asing1001.github.io\node_modules\bluebird\js\release\nodeback.js:42:21
    at E:\Coding\00.Project\asing1001.github.io\node_modules\graceful-fs\graceful-fs.js:78:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)